#!/bin/bash
#command: ls /sys/class/backlight/*/brightness

myscreen=/sys/class/backlight/amdgpu_bl0/brightness


if [ "$1" == "plus" ]; then
     value=$(cat $myscreen)
	 value=$(($value+10))
	echo $value | tee $myscreen
	notify-send -t 500 -u low "$(cat $myscreen)"
elif [ "$1" == "moins" ]; then
     value=$(cat $myscreen)
	 value=$(($value-10))
	echo $value | tee $myscreen
	notify-send -t 500 -u low "$(cat $myscreen)"
elif [ "$1" == "activate" ]; then
	#sudo su
	sudo chmod o+w /sys/class/backlight/amdgpu_bl0/brightness
	#exit
else
	 value=$1
	echo $value | tee $myscreen
	notify-send -t 500 -u low "$(cat $myscreen)"
fi

