#!/bin/python3
import sys
import openai
openai.api_key = "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"


def ask(prompt):
    response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=prompt,
            max_tokens=2000,
            temperature=0.5)
    return response["choices"][0]["text"]


res = ask(" ".join(sys.argv))
print(res)
