#!/bin/python3
import sys
import openai
openai.api_key = "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"


def ask(prompt):
    response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=prompt,
            max_tokens=2000,
            temperature=0.5)
    return response["choices"][0]["text"]


res = ask(" ".join(sys.argv))
print(res)
