#!/bin/bash

lefttop=$(identify $1 | awk " { printf \$4 }")

left=$(($(echo $lefttop | sed -e "s/[0-9]\+x[0-9]\++\([0-9]\+\)+\([0-9]\+\)/\1/")+$4))
top=$(($(echo $lefttop | sed -e "s/[0-9]\+x[0-9]\++\([0-9]\+\)+\([0-9]\+\)/\2/")+$5))

convert $1 -crop $2x$3+$left+$top ${1%.*}_cropped.${1##*.}
