#!/bin/bash

if [ "$1" == "1" ]; then
	# bouton 1
	xdotool mousemove 82 186
	xdotool click 1
elif [ "$1" == "2" ]; then
	# bouton 2
	xdotool mousemove 82 218
	xdotool click 1
elif [ "$1" == "3" ]; then
	# bouton 3
	xdotool mousemove 82 250
	xdotool click 1
elif [ "$1" == "4" ]; then
	# bouton 4
	xdotool mousemove 82 282
	xdotool click 1
elif [ "$1" == "5" ]; then
	# bouton 5
	xdotool mousemove 82 314
	xdotool click 1
elif [ "$1" == "6" ]; then
	# bouton 6
	xdotool mousemove 82 346
	xdotool click 1
elif [ "$1" == "7" ]; then
	# bouton 7
	xdotool mousemove 82 378
	xdotool click 1
elif [ "$1" == "8" ]; then
	# bouton 8
	xdotool mousemove 82 410
	xdotool click 1
elif [ "$1" == "9" ]; then
	# bouton 9
	xdotool mousemove 82 442
	xdotool click 1
elif [ "$1" == "0" ]; then
	# bouton 10
	xdotool mousemove 82 474
	xdotool click 1
elif [ "$1" == "k" ]; then
	# bouton 10
	xdotool mousemove 82 202
	xdotool click 1
fi

