#!/bin/python3

import os

my_list = os.listdir('.')

for oldFileName in my_list:
    newFileName = oldFileName.replace(" ", "_").replace("'", "_")
    if oldFileName != newFileName:
        os.rename(oldFileName, newFileName)
