#!/bin/bash

source ~/sh/theme_module/kitty_theme
source ~/sh/theme_module/feh_theme
source ~/sh/theme_module/i3_theme
source ~/sh/theme_module/neofetch_theme
source ~/sh/theme_module/zathura_theme
source ~/sh/theme_module/rofi_theme
source ~/sh/theme_module/background_theme
source ~/sh/theme_module/vim_theme

getThemeElement (){ 
	cat /home/fabrice/themes/templates/$1 | sed -n "$2p" | sed -e "s/[^:]\+: \(.\+\)$/\1/" 
}

get_color (){
	case "$1" in
			"background")
				index=2 ;;
			"foreground")
				index=3 ;;
			"leadcolor")
				index=4 ;;
			"commentcolor")
				index=5 ;;
			"secondarycolor")
				index=6 ;;
			"colorspec")
				index=7 ;;
			"discretcolor")
				index=8 ;;
			"yellow")
				index=9 ;;
			"blue")
				index=10 ;;
			*)
				echo "choose a color"
	esac
	getThemeElement $selectedtheme $index
}


#selection de thèmes
selectedtheme=$(ls /home/fabrice/themes/templates/ | rofi -dmenu)
#selectedtheme=red.css

#background image
backgroundimage=$(getThemeElement $selectedtheme 11)

#background image
opacity=$(getThemeElement $selectedtheme 12)

# lancement des thèmes
set_kitty_theme
set_feh_theme
set_neofetch_theme
set_zathura_theme
set_i3_theme
set_rofi_theme
set_vim_theme

/home/fabrice/sh/scripts/generatei3
