#!/bin/bash

if [[ "$1" == "-h" ]]; then
       echo "thumbnail [image] [fontsize] [color] [fontfamily] [ text]"
   else
	convert $1 -resize 1280x720 ${1##*/}
	image=${1##*/}
	fontsize=$2
	color=$3
	fontfamily=$4

	shift
	shift
	shift
	shift

	text=$@

	imageshape=($(identify $image | grep -o "[0-9]\+x[0-9]\+" | head -n 1 | tr "x" "\n"))

	echo "
	<svg width='${imageshape[0]}' height='${imageshape[1]}'>
	<text x='50%' y='50%' text-anchor='middle' dominant-baseline='middle' font-size='$fontsize' fill='$color' font-family='$fontfamily' font-weight='bold'>
	$text 
	</text>
	</svg>" > img.svg

	# convert the image
	inkscape -z -e out.png img.svg

	# overlay images
	thumbnailname=${text// /_}.png
	composite out.png $image $thumbnailname

	# open the image
	feh $thumbnailname

	# delete the rest
	rm img.svg out.png
fi
