#!/bin/bash
#switch absolute relative

if [ "$(xsetwacom get 10 Mode | grep Absolute)" == "Absolute" ]; then
	#switching to relative
	for i in $(xsetwacom list devices | grep -e "id: \w\w" -o | sed "s/id: \(\w\w\)/\1/");
	do
		xsetwacom set $i Mode Relative
	done
else
	#switching to absolute
	for i in $(xsetwacom list devices | grep -e "id: \w\w" -o | sed "s/id: \(\w\w\)/\1/");
	do
		xsetwacom set $i Mode Absolute
	done
fi


