#!/bin/bash
tmux new-session -d -s multimedia_security_and_privacy -n notebook
tmux send-keys -t multimedia_security_and_privacy 'vim /home/fabrice/sessions/projet/multimedia_security_and_privacy/note.md' Enter
