#!/bin/bash
firefox https://satomitlearning.sharepoint.com/:x:/r/sites/EstiamAdmin/_layouts/15/doc2.aspx?sourcedoc=%7B16E986DC-91D9-4C2E-B9AD-C1CE67180E1F%7D&file=ESTIAM%20-%20Calendriers%20cours%202022-2023.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1666721091827&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=4517e232-294b-4ff4-b4b9-dc88d8d57b7d &
