#!/bin/bash
firefox -new-tab https://satomitlearning-my.sharepoint.com/:x:/r/personal/yining_hsiao_satom_ch/_layouts/15/Doc.aspx?sourcedoc=%7B6ECD3C1E-092E-43DD-9421-27E8AB55B5D7%7D&file=Formation%20Calendar%202022-2023.xlsx&action=default&mobileredirect=true &

