#!/bin/bash
screen=$(xrandr | grep " connected " | sed "s/\([^ ]\) connected .*/\1/" | rofi -dmenu)

#xrandr --output eDP --mode 1920x1080 --scale 1x1 --output HDMI-A-0 --same-as eDP --mode 1920x1080 --scale 1x1

xrandr --output $screen --same-as eDP --scale 1x1


