#!/bin/bash
firefox -new-tab https://satomitlearning.sharepoint.com/:w:/r/sites/Contenudeformation/_layouts/15/Doc.aspx?sourcedoc=%7B6E908915-46CC-423F-8A3C-C13F92D53A7F%7D&file=Hackathon%20CFCI-E1%20juin%202024%20-%20Document%20en%20cours%20.docx&fromShare=true&action=default&mobileredirect=true &

