#!/bin/bash
#query=$(echo $@ | sed -e "s/ /%/g")

firefox https://translate.google.com/?hl=fr&sl=rw&tl=fr&text=$@&op=translate &

link="https://translate.google.com/?hl=fr&sl=rw&tl=fr&text=$@&op=translate &"

echo $link | xclip -sel clip
sleep 2
xdotool key ctrl+l
sleep 0.4
xdotool key ctrl+v
sleep 0.3
xdotool key Return
