#!/bin/bash
firefox -new-tab https://unigech-my.sharepoint.com/personal/ayoub_hayyane_etu_unige_ch/_layouts/15/onedrive.aspx?e=5%3A71a1c58ee4724749ad1419b6daf6f4c1&sharingv2=true&fromShare=true&at=9&cid=49a51127%2De151%2D4861%2D8aa4%2Da94729c5e299&id=%2Fpersonal%2Fayoub%5Fhayyane%5Fetu%5Funige%5Fch%2FDocuments%2FAssociatif%20et%20num%C3%A9rique&FolderCTID=0x012000F525283DF6122E478F40D40530FC5E67&view=0 &

