#!/bin/bash
firefox -new-tab https://unigech-my.sharepoint.com/:p:/r/personal/moises_palacios_etu_unige_ch/_layouts/15/Doc.aspx?sourcedoc=%7B76E24C77-89E3-4D5D-9728-8F6E6F2FDA6B%7D&file=Pr%C3%A9sentation2.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1&web=1 &

