all:start

start: FORCE
	echo hello

FORCE: 

add: FORCE
	python3 extension_software_manager.py add one two

get: FORCE
	python3 extension_software_manager.py one

delete: FORCE
	python3 extension_software_manager.py delete one two
